name: nipaplay
description: "PlayTorrio Video Player"
publish_to: 'none'

version: 1.8.20

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  window_manager: ^0.4.3
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  path_provider: ^2.1.2
  path: ^1.9.1
  glassmorphism: ^3.0.0
  
  # Media playback
  media_kit: 
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video

  # Dependencies needed by existing code (kept for compatibility)
  http: ^1.3.0
  dio: ^5.1.0
  xml: ^6.5.0
  webdav_client: ^1.2.2
  crypto: ^3.0.3
  cached_network_image: ^3.4.1
  file_picker: ^8.0.6
  file_selector: ^1.0.3
  image: ^4.5.4
  intl: ^0.20.2
  uuid: ^4.5.1
  wakelock_plus: ^1.3.2
  screen_brightness: ^2.1.3
  volume_controller: ^3.4.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  video_player: 2.9.5
  fvp: ^0.33.1
  hotkey_manager: ^0.2.3
  fluent_ui: ^4.12.0
  ffi: ^2.1.3
  smb_connect: ^0.0.9
  nipaplay_smb2:
    path: packages/nipaplay_smb2
  kmbal_ionicons: ^1.0.0
  permission_handler: ^12.0.0+1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  url_launcher: ^6.3.1
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  math_expressions: 2.3.1
  fluent_ui: 4.11.0
  media_kit:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/macos/media_kit_libs_macos_video
  smb_connect:
    path: third_party/smb_connect
